import type { Trip, Car, Testimonial } from './types'

export const trips: Trip[] = [
  {
    id: '1',
    title: 'East Europe Adventure',
    slug: 'east-europe-adventure',
    destination: 'East Europe',
    duration: '10 Hari 9 Malam',
    price: 25000000,
    originalPrice: 28000000,
    image: 'https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=800&q=80',
      'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800&q=80',
      'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&q=80',
    ],
    availableSlots: 8,
    totalSlots: 15,
    departureDates: ['2026-06-15', '2026-07-20', '2026-08-10'],
    meetingPoint: 'Bandara Soekarno-Hatta Terminal 3',
    itinerary: [
      {
        day: 1,
        title: 'Jakarta - Prague',
        description: 'Perjalanan menuju Prague, ibu kota Republik Ceko',
        activities: ['Check-in bandara', 'Penerbangan ke Prague', 'Transit di Dubai'],
      },
      {
        day: 2,
        title: 'Prague City Tour',
        description: 'Menjelajahi keindahan kota Prague',
        activities: ['Charles Bridge', 'Old Town Square', 'Prague Castle', 'St. Vitus Cathedral'],
      },
      {
        day: 3,
        title: 'Prague - Vienna',
        description: 'Perjalanan menuju Vienna, Austria',
        activities: ['Cesky Krumlov', 'Perjalanan ke Vienna', 'Dinner di Vienna'],
      },
    ],
    includes: ['Tiket pesawat PP', 'Hotel bintang 4', 'Makan sesuai program', 'Tour guide berbahasa Indonesia', 'Transportasi AC', 'Tiket masuk objek wisata'],
    excludes: ['Visa Schengen', 'Tips guide dan driver', 'Pengeluaran pribadi', 'Asuransi perjalanan'],
    category: 'international',
    featured: true,
    description: 'Nikmati petualangan tak terlupakan menjelajahi keindahan arsitektur bersejarah dan budaya Eropa Timur yang mempesona. Perjalanan mencakup kota-kota ikonik seperti Prague dan Vienna dengan fasilitas premium dan pemandu profesional.',
    terms: '1. Pendaftaran ditutup H-30 sebelum keberangkatan untuk pengurusan visa.\n2. Pembatalan oleh peserta setelah visa terbit akan dikenakan denda 100% biaya paket.\n3. Uang muka (DP) bersifat Non-Refundable kecuali pembatalan sepihak oleh pihak penyelenggara.\n4. Tiket penerbangan kelas ekonomi dan bagasi 20kg sudah termasuk.',
  },
  {
    id: '2',
    title: 'Bromo Sunrise & Yogyakarta Heritage',
    slug: 'bromo-yogya-heritage',
    destination: 'Bromo - Yogyakarta',
    duration: '4 Hari 3 Malam',
    price: 3500000,
    image: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&q=80',
      'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=800&q=80',
      'https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800&q=80',
    ],
    availableSlots: 4,
    totalSlots: 12,
    departureDates: ['2026-05-25', '2026-06-08', '2026-06-22', '2026-07-06'],
    meetingPoint: 'Stasiun Surabaya Gubeng',
    itinerary: [
      {
        day: 1,
        title: 'Surabaya - Bromo',
        description: 'Perjalanan menuju kawasan Bromo',
        activities: ['Penjemputan di Surabaya', 'Perjalanan ke Bromo', 'Check-in hotel', 'Free time'],
      },
      {
        day: 2,
        title: 'Bromo Sunrise',
        description: 'Menyaksikan sunrise legendaris di Bromo',
        activities: ['Sunrise di Penanjakan', 'Jeep tour ke kawah Bromo', 'Savana & Pasir Berbisik', 'Perjalanan ke Yogya'],
      },
      {
        day: 3,
        title: 'Yogyakarta Heritage',
        description: 'Menjelajahi warisan budaya Yogyakarta',
        activities: ['Candi Borobudur', 'Candi Prambanan', 'Malioboro', 'Kuliner Gudeg'],
      },
      {
        day: 4,
        title: 'Yogyakarta - Pulang',
        description: 'Hari terakhir tour',
        activities: ['Keraton Yogyakarta', 'Taman Sari', 'Transfer ke bandara/stasiun'],
      },
    ],
    includes: ['Transportasi AC', 'Jeep Bromo', 'Hotel bintang 3', 'Makan sesuai program', 'Tour guide lokal', 'Tiket masuk wisata'],
    excludes: ['Tiket pesawat/kereta', 'Tips guide dan driver', 'Pengeluaran pribadi'],
    category: 'domestic',
    featured: true,
    description: 'Petualangan seru menyaksikan matahari terbit (sunrise) yang megah di Gunung Bromo dilanjutkan dengan petualangan budaya menelusuri keindahan candi bersejarah di Yogyakarta. Kombinasi petualangan alam dan budaya yang sempurna.',
    terms: '1. Pelunasan biaya trip wajib diselesaikan maksimal H-7 sebelum keberangkatan.\n2. Pembatalan kurang dari H-3 sebelum keberangkatan dikenakan denda 100%.\n3. Peserta diharapkan dalam kondisi fisik yang sehat untuk menanjak di kawasan Bromo.\n4. Membawa pakaian hangat, jaket, dan sarung tangan.',
  },
  {
    id: '3',
    title: 'Dieng Plateau & Yogyakarta Culture',
    slug: 'dieng-yogya-culture',
    destination: 'Dieng - Yogyakarta',
    duration: '3 Hari 2 Malam',
    price: 2800000,
    image: 'https://images.unsplash.com/photo-1584810359583-96fc3448beaa?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1584810359583-96fc3448beaa?w=800&q=80',
      'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=800&q=80',
    ],
    availableSlots: 6,
    totalSlots: 10,
    departureDates: ['2026-06-01', '2026-06-15', '2026-07-01'],
    meetingPoint: 'Bandara Adi Soemarmo Solo',
    itinerary: [
      {
        day: 1,
        title: 'Solo - Dieng',
        description: 'Perjalanan menuju dataran tinggi Dieng',
        activities: ['Penjemputan di Solo', 'Perjalanan ke Dieng', 'Telaga Warna', 'Kawah Sikidang'],
      },
      {
        day: 2,
        title: 'Dieng - Yogyakarta',
        description: 'Eksplorasi Dieng dan perjalanan ke Yogya',
        activities: ['Golden Sunrise Sikunir', 'Candi Arjuna', 'Perjalanan ke Yogyakarta', 'Malioboro'],
      },
      {
        day: 3,
        title: 'Yogyakarta - Pulang',
        description: 'Hari terakhir tour',
        activities: ['Candi Borobudur', 'Oleh-oleh khas Yogya', 'Transfer ke bandara'],
      },
    ],
    includes: ['Transportasi AC', 'Hotel bintang 3', 'Makan sesuai program', 'Tour guide lokal', 'Tiket masuk wisata'],
    excludes: ['Tiket pesawat/kereta', 'Tips guide dan driver', 'Pengeluaran pribadi'],
    category: 'domestic',
    featured: true,
    description: 'Menyusuri dataran tinggi Dieng yang berjuluk Negeri di Atas Awan, menikmati keindahan Telaga Warna, Kawah Sikidang yang aktif, serta kehangatan budaya lokal di Yogyakarta. Destinasi alam pegunungan yang menyejukkan hati.',
    terms: '1. Pembayaran DP minimal 20% dari total biaya paket.\n2. Pembatalan oleh peserta dapat dialihkan ke jadwal lain dengan konfirmasi maksimal H-14.\n3. Pihak travel berhak membatalkan perjalanan jika terjadi keadaan kahar (force majeure).\n4. Perlengkapan pribadi dan obat-obatan khusus harap dibawa masing-masing.',
  },
  {
    id: '4',
    title: 'Bali Paradise Escape',
    slug: 'bali-paradise-escape',
    destination: 'Bali',
    duration: '5 Hari 4 Malam',
    price: 4500000,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
      'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=80',
    ],
    availableSlots: 10,
    totalSlots: 15,
    departureDates: ['2026-06-10', '2026-07-05', '2026-08-01'],
    meetingPoint: 'Bandara Ngurah Rai Bali',
    itinerary: [
      {
        day: 1,
        title: 'Arrival Bali',
        description: 'Tiba di Pulau Dewata',
        activities: ['Airport pickup', 'Check-in hotel', 'Pantai Kuta', 'Dinner'],
      },
      {
        day: 2,
        title: 'Ubud Tour',
        description: 'Menjelajahi keindahan Ubud',
        activities: ['Tegallalang Rice Terrace', 'Tirta Empul', 'Ubud Monkey Forest', 'Ubud Palace'],
      },
    ],
    includes: ['Transportasi AC', 'Hotel bintang 4', 'Makan sesuai program', 'Tour guide', 'Tiket masuk wisata'],
    excludes: ['Tiket pesawat', 'Tips guide dan driver', 'Pengeluaran pribadi', 'Water sports'],
    category: 'domestic',
    featured: false,
    description: 'Melarikan diri ke surga tropis Bali. Menjelajahi keasrian persawahan terasering Ubud, keagungan istana, dan menikmati keindahan sunset di tepi Pantai Kuta yang legendaris. Pengalaman liburan santai yang sangat berkesan.',
    terms: '1. Harga berlaku untuk per pax dengan minimal keberangkatan sesuai kuota.\n2. Anak-anak di bawah 5 tahun mendapatkan potongan harga khusus.\n3. Protokol kesehatan dan kebersihan hotel bintang 4 wajib dipatuhi.\n4. Pengeluaran di luar program makan yang disediakan merupakan tanggung jawab pribadi.',
  },
  {
    id: '5',
    title: 'Raja Ampat Diving Paradise',
    slug: 'raja-ampat-diving',
    destination: 'Raja Ampat',
    duration: '6 Hari 5 Malam',
    price: 15000000,
    image: 'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=800&q=80',
    availableSlots: 5,
    totalSlots: 8,
    departureDates: ['2026-07-15', '2026-08-20'],
    meetingPoint: 'Bandara Domine Eduard Osok Sorong',
    itinerary: [
      {
        day: 1,
        title: 'Sorong - Waisai',
        description: 'Perjalanan menuju Raja Ampat',
        activities: ['Airport pickup', 'Ferry ke Waisai', 'Check-in resort'],
      },
    ],
    includes: ['Transportasi laut', 'Resort', 'Makan 3x sehari', 'Snorkeling equipment', 'Guide lokal'],
    excludes: ['Tiket pesawat', 'Diving equipment', 'Pengeluaran pribadi'],
    category: 'domestic',
    featured: false,
    description: 'Menyelam di salah satu surga bawah laut terbaik di dunia. Gugusan karst Raja Ampat yang spektakuler dan keanekaragaman terumbu karang yang melimpah siap memanjakan para diver dan pencinta keindahan bahari Indonesia.',
    terms: '1. Peserta wajib memiliki lisensi diving aktif untuk program diving.\n2. Wajib membawa kartu identitas diri yang berlaku (KTP/Paspor).\n3. Biaya konservasi Raja Ampat (PIN) sudah termasuk untuk turis domestik.\n4. Pembatalan sepihak oleh peserta H-14 dikenakan biaya hangus 50%.',
  },
]

export const cars: Car[] = [
  {
    id: '1',
    name: 'Toyota Hiace Premio',
    type: 'Van',
    capacity: 14,
    pricePerDay: 1500000,
    image: 'https://images.unsplash.com/photo-1609520505218-7421df70ba5d?w=800&q=80',
    features: ['AC', 'Reclining Seat', 'Audio System', 'USB Charger', 'WiFi'],
  },
  {
    id: '2',
    name: 'Toyota Innova Reborn',
    type: 'MPV',
    capacity: 7,
    pricePerDay: 800000,
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80',
    features: ['AC', 'Leather Seat', 'Audio System', 'USB Charger'],
  },
  {
    id: '3',
    name: 'Toyota Alphard',
    type: 'Luxury MPV',
    capacity: 7,
    pricePerDay: 2500000,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
    features: ['AC', 'Premium Leather Seat', 'Premium Audio', 'Captain Seat', 'WiFi', 'TV'],
  },
  {
    id: '4',
    name: 'Mercedes Sprinter',
    type: 'Van',
    capacity: 16,
    pricePerDay: 2000000,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    features: ['AC', 'Reclining Seat', 'Premium Audio', 'WiFi', 'Toilet'],
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Wijaya',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80',
    location: 'Jakarta',
    rating: 5,
    comment: 'Pengalaman trip ke East Europe bersama Airlangga Travel luar biasa! Guide yang ramah, itinerary yang well-planned, dan semua berjalan lancar. Pasti akan repeat order!',
    tripTitle: 'East Europe Adventure',
  },
  {
    id: '2',
    name: 'Budi Santoso',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80',
    location: 'Surabaya',
    rating: 5,
    comment: 'Trip Bromo-Yogya sangat memorable! Sunrise di Bromo indah banget, guide nya juga sangat informatif. Worth every penny!',
    tripTitle: 'Bromo Sunrise & Yogyakarta Heritage',
  },
  {
    id: '3',
    name: 'Linda Permata',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80',
    location: 'Bandung',
    rating: 5,
    comment: 'Sudah 3x ikut open trip sama Airlangga Travel dan selalu puas. Pelayanan prima, harga bersaing, dan yang paling penting aman dan nyaman.',
    tripTitle: 'Dieng Plateau & Yogyakarta Culture',
  },
  {
    id: '4',
    name: 'Ahmad Rizki',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80',
    location: 'Medan',
    rating: 5,
    comment: 'Private trip ke Bali dengan keluarga sangat memuaskan. Semua request kami dipenuhi dengan baik. Terima kasih Airlangga Travel!',
    tripTitle: 'Bali Private Trip',
  },
]

export const stats = [
  { label: 'Trips', value: '500+', icon: 'plane' },
  { label: 'Travelers', value: '10k+', icon: 'users' },
  { label: 'Destinations', value: '50+', icon: 'map-pin' },
  { label: 'Rating', value: '4.9', icon: 'star' },
]

export const features = [
  {
    title: 'Best Destinations',
    description: 'Destinasi wisata terbaik dalam dan luar negeri yang sudah terseleksi',
    icon: 'map',
  },
  {
    title: 'Prima Service',
    description: 'Pelayanan prima dari tim profesional yang berpengalaman',
    icon: 'award',
  },
  {
    title: 'Best Price',
    description: 'Harga terbaik dan transparan tanpa biaya tersembunyi',
    icon: 'tag',
  },
  {
    title: 'Flexible Payment',
    description: 'Pembayaran fleksibel dengan berbagai metode pembayaran',
    icon: 'credit-card',
  },
  {
    title: '24/7 Customer Service',
    description: 'Layanan pelanggan siap membantu kapanpun Anda butuhkan',
    icon: 'headphones',
  },
  {
    title: 'Best Facilities',
    description: 'Fasilitas terbaik untuk kenyamanan perjalanan Anda',
    icon: 'shield-check',
  },
]

export const destinations = [
  { name: 'Bromo', image: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=400&q=80' },
  { name: 'Yogyakarta', image: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=400&q=80' },
  { name: 'Bali', image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400&q=80' },
  { name: 'Raja Ampat', image: 'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=400&q=80' },
  { name: 'Dieng', image: 'https://images.unsplash.com/photo-1584810359583-96fc3448beaa?w=400&q=80' },
  { name: 'East Europe', image: 'https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=400&q=80' },
]

export const privateTripFacilities = [
  { id: 'transport', label: 'Transportasi', price: 500000 },
  { id: 'hotel', label: 'Hotel', price: 800000 },
  { id: 'guide', label: 'Tour Guide', price: 300000 },
  { id: 'meals', label: 'Makan', price: 200000 },
  { id: 'tickets', label: 'Tiket Wisata', price: 150000 },
  { id: 'documentation', label: 'Dokumentasi', price: 250000 },
]
